title: Docs Trial 2
description: Testing out the just-the-docs template
theme: just-the-docs
url: https://soulis-siluos.github.io/docstrial

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

#defaults:
#  - scope:
#      path: "docs" # an empty string here means all files in the project
#      type: "pages"
#    values:
#      layout: "default"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
