title: Docs Trial
description: Testing out the just-the-docs template
theme: just-the-docs

url: https://soulis-siluos.github.io/DOCSTRIAL

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
